version: "3.9"
volumes:
  postgres_db:

networks:
  sui-net:
    driver: bridge

  postgres:
    image: postgres:15
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sui_indexer_db
    expose:
      - 5432
    networks:
      - sui-net
    volumes:
      - postgres_db:/var/lib/postgresql/data:rw
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]

  indexer:
    image: lexprime/sui:latest
    container_name: sui-indexer
    restart: on-failure
    networks:
      - sui-net
    volumes:
      - ./start_indexer.sh:/sui/start_indexer.sh:ro
    tty: true
    command: ["/bin/bash"]
